"""add logo url to user profiles

Revision ID: 42077555fae4
Revises: da7acb6a979c
Create Date: 2026-10-01 11:52:45.308993
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42077555fae4'
down_revision = 'da7acb6a979c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_notifications_user_created'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_user_unread'), table_name='notifications', postgresql_where='(is_read = false)')
    op.drop_index(op.f('idx_approval_stages_admin_status'), table_name='post_approval_stages')
    op.drop_index(op.f('idx_approval_stages_post'), table_name='post_approval_stages')
    op.drop_index(op.f('idx_rag_chat_history_user_created'), table_name='rag_chat_history')
    op.drop_column('scheduled_posts', 'admin_token')
    op.drop_column('scheduled_posts', 'admin_token_used')
    op.add_column('user_profiles', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.drop_index(op.f('idx_users_invite_code'), table_name='users', postgresql_where='(invite_code IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_invite_code'), 'users', ['invite_code'], unique=True, postgresql_where='(invite_code IS NOT NULL)')
    op.drop_column('user_profiles', 'logo_url')
    op.add_column('scheduled_posts', sa.Column('admin_token_used', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('scheduled_posts', sa.Column('admin_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_rag_chat_history_user_created'), 'rag_chat_history', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_approval_stages_post'), 'post_approval_stages', ['scheduled_post_id'], unique=False)
    op.create_index(op.f('idx_approval_stages_admin_status'), 'post_approval_stages', ['admin_status'], unique=False)
    op.create_index(op.f('idx_notifications_user_unread'), 'notifications', ['user_id'], unique=False, postgresql_where='(is_read = false)')
    op.create_index(op.f('idx_notifications_user_created'), 'notifications', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###
