"""add company footer branding

Revision ID: 87968abc51c2
Revises: 42077555fae4
Create Date: 2026-10-01 14:51:42.639746
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87968abc51c2'
down_revision = '42077555fae4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'user_profiles',
    sa.Column(
        'footer_enabled',
        sa.Boolean(),
        nullable=False,
        server_default=sa.false(),
    )
)
    op.add_column('user_profiles', sa.Column('footer_text', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'footer_text')
    op.drop_column('user_profiles', 'footer_enabled')
    # ### end Alembic commands ###
