"""initial schema

Revision ID: da7acb6a979c
Revises: 
Create Date: 2026-09-30 12:33:47.601853
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da7acb6a979c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events_cache', 'event_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('events_cache', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_events_cache_id'), 'events_cache', ['id'], unique=False)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_notifications_user_created'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_user_unread'), table_name='notifications', postgresql_where='(is_read = false)')
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.alter_column('post_approval_stages', 'scheduled_post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('post_approval_stages', 'hr_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('post_approval_stages', 'superadmin_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('post_approval_stages', 'admin_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('post_approval_stages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_approval_stages_admin_status'), table_name='post_approval_stages')
    op.drop_index(op.f('idx_approval_stages_post'), table_name='post_approval_stages')
    op.create_index(op.f('ix_post_approval_stages_id'), 'post_approval_stages', ['id'], unique=False)
    op.alter_column('post_targets', 'scheduled_post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('post_targets', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_index(op.f('ix_post_targets_id'), 'post_targets', ['id'], unique=False)
    op.alter_column('post_templates', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('post_templates', 'platforms',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=False)
    op.alter_column('post_templates', 'recurrence_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'ONE_TIME'::character varying"))
    op.alter_column('post_templates', 'interval_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('post_templates', 'occurrence_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('post_templates', 'timezone',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'UTC'::character varying"))
    op.alter_column('post_templates', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('post_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_post_templates_id'), 'post_templates', ['id'], unique=False)
    op.alter_column('rag_chat_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_rag_chat_history_user_created'), table_name='rag_chat_history')
    op.create_index(op.f('ix_rag_chat_history_id'), 'rag_chat_history', ['id'], unique=False)
    op.alter_column('scheduled_posts', 'template_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('scheduled_posts', 'token_used',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('scheduled_posts', 'superadmin_token_used',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('scheduled_posts', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'scheduled'::character varying"))
    op.alter_column('scheduled_posts', 'ai_generated',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('scheduled_posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_scheduled_posts_id'), 'scheduled_posts', ['id'], unique=False)
    op.drop_column('scheduled_posts', 'admin_token')
    op.drop_column('scheduled_posts', 'admin_token_used')
    op.alter_column('social_accounts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('social_accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('social_accounts_user_id_platform_key'), 'social_accounts', type_='unique')
    op.create_index(op.f('ix_social_accounts_id'), 'social_accounts', ['id'], unique=False)
    op.alter_column('trends_cache', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_trends_cache_id'), 'trends_cache', ['id'], unique=False)
    op.alter_column('user_profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_profiles', 'posts_per_week',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.alter_column('user_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.alter_column('users', 'timezone',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'UTC'::character varying"))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_users_invite_code'), table_name='users', postgresql_where='(invite_code IS NOT NULL)')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_constraint(op.f('users_admin_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'users', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_admin_id_fkey'), 'users', 'users', ['admin_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_invite_code'), 'users', ['invite_code'], unique=True, postgresql_where='(invite_code IS NOT NULL)')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
    op.alter_column('users', 'timezone',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'UTC'::character varying"))
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.alter_column('user_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_profiles', 'posts_per_week',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('user_profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_trends_cache_id'), table_name='trends_cache')
    op.alter_column('trends_cache', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_social_accounts_id'), table_name='social_accounts')
    op.create_unique_constraint(op.f('social_accounts_user_id_platform_key'), 'social_accounts', ['user_id', 'platform'], postgresql_nulls_not_distinct=False)
    op.alter_column('social_accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('social_accounts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('scheduled_posts', sa.Column('admin_token_used', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('scheduled_posts', sa.Column('admin_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_scheduled_posts_id'), table_name='scheduled_posts')
    op.alter_column('scheduled_posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scheduled_posts', 'ai_generated',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('scheduled_posts', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'scheduled'::character varying"))
    op.alter_column('scheduled_posts', 'superadmin_token_used',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('scheduled_posts', 'token_used',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('scheduled_posts', 'template_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_rag_chat_history_id'), table_name='rag_chat_history')
    op.create_index(op.f('idx_rag_chat_history_user_created'), 'rag_chat_history', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('rag_chat_history', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_post_templates_id'), table_name='post_templates')
    op.alter_column('post_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('post_templates', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('post_templates', 'timezone',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'UTC'::character varying"))
    op.alter_column('post_templates', 'occurrence_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('post_templates', 'interval_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('post_templates', 'recurrence_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'ONE_TIME'::character varying"))
    op.alter_column('post_templates', 'platforms',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False)
    op.alter_column('post_templates', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_post_targets_id'), table_name='post_targets')
    op.alter_column('post_targets', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('post_targets', 'scheduled_post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_post_approval_stages_id'), table_name='post_approval_stages')
    op.create_index(op.f('idx_approval_stages_post'), 'post_approval_stages', ['scheduled_post_id'], unique=False)
    op.create_index(op.f('idx_approval_stages_admin_status'), 'post_approval_stages', ['admin_status'], unique=False)
    op.alter_column('post_approval_stages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('post_approval_stages', 'admin_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('post_approval_stages', 'superadmin_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('post_approval_stages', 'hr_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('post_approval_stages', 'scheduled_post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.create_index(op.f('idx_notifications_user_unread'), 'notifications', ['user_id'], unique=False, postgresql_where='(is_read = false)')
    op.create_index(op.f('idx_notifications_user_created'), 'notifications', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_events_cache_id'), table_name='events_cache')
    op.alter_column('events_cache', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('events_cache', 'event_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
