"""add footer url to user profiles

Revision ID: f7ba3b1f4985
Revises: 87968abc51c2
Create Date: 2026-10-01 15:25:30.444783
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ba3b1f4985'
down_revision = '87968abc51c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('footer_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'footer_url')
    # ### end Alembic commands ###
