"""add overlay text branding

Revision ID: fa2418e7ca63
Revises: f7ba3b1f4985
Create Date: 2026-10-05 09:56:05.305072
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa2418e7ca63'
down_revision = 'f7ba3b1f4985'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('overlay_text', sa.String(length=500), nullable=True))
    op.add_column(
    'user_profiles',
    sa.Column(
        'overlay_position',
        sa.String(length=50),
        server_default='bottom-center',
        nullable=False
    )
     )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'overlay_position')
    op.drop_column('user_profiles', 'overlay_text')
    # ### end Alembic commands ###
